### ISSUE TITLE
Not an issue, but a huge thanks.

### ISSUE THREAD

**Issue by btg611** [ZZ-Cat/raildriver#20]
Wasn't sure of the best way to get in contact with you here, so I figured I'd leave this here. Huge thanks for doing this. This is something I had been considering doing myself for the longest time but was never motivated enough or quite sure how to go about it. Today I decided to google it to see if it had been done, and that's how I found this. Kudos to you for taking this project on, I look forward to using this!

**Comment by ZZ-Cat** [comment]
You're quite welcome, bud. =^/.^=

RailDriver was born out of necessity for me, as for six years I didn't have internet at my place & I had no way of downloading Magnum's RLC Platinum Gamma E2.

So, I decided to basically roll my own.
